#!/usr/bin/env python3
"""Generate a README.md with GitHub traffic statistics."""

import csv
from collections import defaultdict
from pathlib import Path


def read_csv(filepath):
    rows = []
    with open(filepath, newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            rows.append(row)
    return rows


def get_date_range(data_dir):
    all_dates = set()
    for csv_file in Path(data_dir, "views").glob("*.csv"):
        for row in read_csv(csv_file):
            if row.get("date"):
                all_dates.add(row["date"])
    if not all_dates:
        return "N/A", "N/A"
    return min(all_dates), max(all_dates)


def aggregate_views_clones(data_dir, metric):
    results = {}
    for csv_file in Path(data_dir, metric).glob("*.csv"):
        repo = csv_file.stem
        total_count = 0
        total_uniques = 0
        for row in read_csv(csv_file):
            try:
                total_count += int(row.get("count", 0) or 0)
                total_uniques += int(row.get("uniques", 0) or 0)
            except ValueError:
                continue
        if total_count > 0:
            results[repo] = {"count": total_count, "uniques": total_uniques}
    return dict(sorted(results.items(), key=lambda x: x[1]["count"], reverse=True))


def aggregate_referrers(data_dir):
    ref_totals = defaultdict(lambda: defaultdict(lambda: {"count": 0, "uniques": 0}))
    for csv_file in Path(data_dir, "referrers").glob("*.csv"):
        repo = csv_file.stem
        for row in read_csv(csv_file):
            for i in range(1, 11):
                ref = row.get(f"ref_{i}", "").strip()
                count = row.get(f"ref_{i}_count", "")
                uniques = row.get(f"ref_{i}_uniques", "")
                if ref and count:
                    try:
                        ref_totals[repo][ref]["count"] += int(count)
                        ref_totals[repo][ref]["uniques"] += int(uniques or 0)
                    except ValueError:
                        continue
    return ref_totals


def generate_readme(data_dir="data"):
    start_date, end_date = get_date_range(data_dir)
    views = aggregate_views_clones(data_dir, "views")
    clones = aggregate_views_clones(data_dir, "clones")
    referrers = aggregate_referrers(data_dir)

    lines = [
        "# GitHub Traffic Stats",
        "",
        f"**Data range:** `{start_date}` to `{end_date}`",
        "",
        "Auto-generated from [GitHub Traffic API](https://docs.github.com/en/rest/metrics/traffic) data collected daily via GitHub Actions.",
        "",
        "---",
        "",
        "## Top Repositories by Views",
        "",
        "| # | Repository | Views | Unique Visitors |",
        "|---|-----------|-------|-----------------|",
    ]

    for i, (repo, stats) in enumerate(list(views.items())[:20], 1):
        lines.append(
            f"| {i} | [{repo}](https://github.com/Chocapikk/{repo}) "
            f"| {stats['count']:,} | {stats['uniques']:,} |"
        )

    lines.extend(
        [
            "",
            "---",
            "",
            "## Top Repositories by Clones",
            "",
            "| # | Repository | Clones | Unique Cloners |",
            "|---|-----------|--------|----------------|",
        ]
    )

    for i, (repo, stats) in enumerate(list(clones.items())[:20], 1):
        lines.append(
            f"| {i} | [{repo}](https://github.com/Chocapikk/{repo}) "
            f"| {stats['count']:,} | {stats['uniques']:,} |"
        )

    lines.extend(
        [
            "",
            "---",
            "",
            "## Top Referrers by Repository",
            "",
        ]
    )

    top_repos_by_views = list(views.keys())[:10]
    for repo in top_repos_by_views:
        if repo not in referrers or not referrers[repo]:
            continue
        sorted_refs = sorted(
            referrers[repo].items(), key=lambda x: x[1]["count"], reverse=True
        )[:5]
        if not sorted_refs:
            continue
        lines.append(f"### [{repo}](https://github.com/Chocapikk/{repo})")
        lines.append("")
        lines.append("| Referrer | Views | Unique Visitors |")
        lines.append("|----------|-------|-----------------|")
        for ref, stats in sorted_refs:
            lines.append(f"| {ref} | {stats['count']:,} | {stats['uniques']:,} |")
        lines.append("")

    lines.extend(
        [
            "---",
            "",
            "*Last updated: auto-generated by `generate_readme.py`*",
            "",
        ]
    )

    with open("README.md", "w") as f:
        f.write("\n".join(lines))

    print(
        f"README.md generated ({len(views)} repos tracked, {start_date} to {end_date})"
    )


if __name__ == "__main__":
    generate_readme()
